.PHONY: all clean

all:
	$(MAKE) -C baseline
	$(MAKE) -C xSTM
	$(MAKE) -C handSTM
	$(MAKE) -C STMCAS
	$(MAKE) -C hybrid

clean:
	$(MAKE) -C baseline clean
	$(MAKE) -C xSTM clean
	$(MAKE) -C handSTM clean
	$(MAKE) -C STMCAS clean
	$(MAKE) -C hybrid clean
